server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    driver-class-name: ${sky.datasource.driver-class-name}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 设置是否自动提交事务，默认为true
      auto-commit: true
      # 设置用于测试连接的SQL查询语句
      connection-test-query: SELECT 1
      # 设置获取数据库连接的超时时间，默认为30秒，单位是毫秒
      connection-timeout: 30000
      #设置连接在连接池中保持空闲的最长时间，默认为10分钟，单位是毫秒
      idle-timeout: 30000
      # 设置连接在连接池中允许存在的最长时间，默认为30分钟，单位是毫秒
      max-lifetime: 1800000
      # 设置连接池中允许的最大连接数，默认为10
      maximum-pool-size: 10
      # 设置连接池中保持的最小空闲连接数，默认为10
      minimum-idle: 10
      # 设置连接池的名称，默认为"HikariPool-1"
      pool-name: HikariPool-1
      # 设置连接验证的超时时间，默认为5000（5秒），单位是毫秒
      validation-timeout: 5000
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  minioss:
    access-key-id: ${sky.minioss.access-key-id}
    access-key-secret: ${sky.minioss.access-key-secret}
    bucket-name: ${sky.minioss.bucket-name}
    end-point: ${sky.minioss.end-point}
